export interface Ticket {
  id: string;
  title: string;
  description?: string;
  startDate: Date;
  endDate: Date;
  status: 'in-progress' | 'planned' | 'completed';
  storyPoints: number;
  effortDays?: number;
  assignedTo: string;
  requiredRole?: 'Frontend' | 'Backend' | 'Fullstack' | 'QA' | 'Designer' | 'DataEngineer' | 'iOS' | 'Android';
  acceptanceCriteria?: string; // BDD-style AC generated by PRD pipeline Agent 6
  dependencies?: {
    blockedBy?: string[];  // Ticket IDs that must complete before this
    blocks?: string[];     // Calculated: Tickets waiting on this (auto-populated)
  };
}

export interface Feature {
  id: string;
  name: string;
  tickets: Ticket[];
}

export interface Sprint {
  id: string;
  name: string;
  startDate: Date;
  endDate: Date;
}

// ── Story Point ↔ Days Mapping ──

export type SPMappingPreset = 'fibonacci' | 'linear' | 'custom';

export interface SPMappingEntry {
  sp: number;
  days: number;
}

export interface StoryPointMapping {
  preset: SPMappingPreset;
  entries: SPMappingEntry[];
}

export const SP_PRESETS: Record<Exclude<SPMappingPreset, 'custom'>, StoryPointMapping> = {
  fibonacci: {
    preset: 'fibonacci',
    entries: [
      { sp: 1, days: 0.5 },
      { sp: 2, days: 1 },
      { sp: 3, days: 2 },
      { sp: 5, days: 3 },
      { sp: 8, days: 5 },
      { sp: 13, days: 8 },
    ],
  },
  linear: {
    preset: 'linear',
    entries: [
      { sp: 1, days: 1 },
      { sp: 2, days: 2 },
      { sp: 3, days: 3 },
      { sp: 5, days: 5 },
      { sp: 8, days: 8 },
      { sp: 13, days: 13 },
    ],
  },
};

export function storyPointsToDays(sp: number, mapping?: StoryPointMapping): number {
  if (!mapping || mapping.entries.length === 0) return sp;
  const entries = mapping.entries;
  const exact = entries.find(e => e.sp === sp);
  if (exact) return exact.days;
  if (sp <= entries[0].sp) return (sp / entries[0].sp) * entries[0].days;
  const last = entries[entries.length - 1];
  if (sp >= last.sp) return (sp / last.sp) * last.days;
  for (let i = 0; i < entries.length - 1; i++) {
    if (sp > entries[i].sp && sp < entries[i + 1].sp) {
      const ratio = (sp - entries[i].sp) / (entries[i + 1].sp - entries[i].sp);
      return entries[i].days + ratio * (entries[i + 1].days - entries[i].days);
    }
  }
  return sp;
}

export interface Release {
  id: string;
  name: string;
  startDate: Date;
  endDate: Date;
  features: Feature[];
  sprints?: Sprint[];
  storyPointMapping?: StoryPointMapping;
  milestones: Milestone[];
  phases?: Phase[];
}

export interface Product {
  id: string;
  name: string;
  releases: Release[];
}

export interface PTOEntry {
  id: string;
  name: string;
  startDate: Date;
  endDate: Date;
}

export interface TeamMember {
  id: string;
  name: string;
  role: 'Developer' | 'Designer' | 'QA' | 'Frontend' | 'Backend' | 'Fullstack' | 'DataEngineer' | 'iOS' | 'Android';
  experienceLevel?: 'Junior' | 'Mid' | 'Senior' | 'Lead';
  notes?: string;
  pto: PTOEntry[];
  productId: string;
  velocityMultiplier?: number;
}

export interface Holiday {
  id: string;
  name: string;
  startDate: Date;
  endDate: Date;
}

// ── Milestones ──

export type MilestoneType = 'Testing' | 'Deployment' | 'Approval' | 'Freeze' | 'Launch' | 'Other';

export interface Milestone {
  id: string;
  releaseId: string;
  name: string;
  type: MilestoneType;
  dateType: 'single' | 'range';
  startDate: Date;
  endDate?: Date;
  description?: string;
  isBlocking?: boolean;
  order?: number;
}

// ── Phases ──

export type PhaseType = 'DevWindow' | 'Testing' | 'Deployment' | 'Approval' | 'Launch' | 'Custom';

export interface Phase {
  id: string;
  releaseId: string;
  name: string;
  type: PhaseType;
  startDate: Date;
  endDate: Date;
  allowsWork: boolean;
  order: number;
  description?: string;
}

export function getMockPhasesForRelease(release: Release): Phase[] {
  const goLiveDate = new Date(release.endDate);
  
  const uatEnd = new Date(goLiveDate);
  uatEnd.setDate(uatEnd.getDate() - 1);
  const uatStart = new Date(uatEnd);
  uatStart.setDate(uatStart.getDate() - 13);
  
  const sitEnd = new Date(uatStart);
  sitEnd.setDate(sitEnd.getDate() - 1);
  const sitStart = new Date(sitEnd);
  sitStart.setDate(sitStart.getDate() - 13);
  
  const devEnd = new Date(sitStart);
  devEnd.setDate(devEnd.getDate() - 1);
  const devStart = new Date(release.startDate);
  
  return [
    {
      id: `phase-dev-${release.id}`,
      releaseId: release.id,
      name: 'Dev Window',
      type: 'DevWindow',
      startDate: devStart,
      endDate: devEnd,
      allowsWork: true,
      order: 1,
    },
    {
      id: `phase-sit-${release.id}`,
      releaseId: release.id,
      name: 'SIT',
      type: 'Testing',
      startDate: sitStart,
      endDate: sitEnd,
      allowsWork: false,
      order: 2,
    },
    {
      id: `phase-uat-${release.id}`,
      releaseId: release.id,
      name: 'UAT',
      type: 'Testing',
      startDate: uatStart,
      endDate: uatEnd,
      allowsWork: false,
      order: 3,
    },
    {
      id: `phase-golive-${release.id}`,
      releaseId: release.id,
      name: 'Go-Live',
      type: 'Launch',
      startDate: goLiveDate,
      endDate: goLiveDate,
      allowsWork: false,
      order: 4,
    },
  ];
}

// ===========================================
// FRESH MOCK DATA — 2 WEB + 1 MOBILE PRODUCT
// ===========================================

// ===========================================
// PRODUCT 1: 🚀 TASKFLOW PRO (WEB — PROJECT MANAGEMENT)
// ===========================================
const product1: Product = {
  id: 'taskflow-01',
  name: '🚀 TaskFlow Pro — Project Management',
  releases: [
    {
      id: 'tf-rel-1',
      name: 'v1.0 — Core Boards & Tasks',
      startDate: new Date('2026-01-12'),
      endDate: new Date('2026-03-27'),
      storyPointMapping: SP_PRESETS.fibonacci,
      milestones: [
        {
          id: 'tf-ms-1',
          releaseId: 'tf-rel-1',
          name: 'Code Freeze',
          type: 'Freeze',
          dateType: 'single',
          startDate: new Date('2026-03-13'),
          description: 'Feature complete — no new scope',
          isBlocking: true,
          order: 1
        },
        {
          id: 'tf-ms-2',
          releaseId: 'tf-rel-1',
          name: 'UAT Sign-off',
          type: 'Approval',
          dateType: 'single',
          startDate: new Date('2026-03-20'),
          description: 'Stakeholder sign-off required',
          isBlocking: true,
          order: 2
        },
        {
          id: 'tf-ms-3',
          releaseId: 'tf-rel-1',
          name: 'Production Launch',
          type: 'Launch',
          dateType: 'single',
          startDate: new Date('2026-03-27'),
          description: 'Go-live to production',
          isBlocking: false,
          order: 3
        }
      ],
      features: [
        {
          id: 'tf-f1',
          name: '📋 Task Board',
          tickets: [
            {
              id: 'tf-t1',
              title: 'Board data model & REST API',
              description: 'PostgreSQL schema + CRUD endpoints for boards, columns, tasks',
              startDate: new Date('2026-01-12'),
              endDate: new Date('2026-01-16'),
              status: 'completed',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Alex Chen',
              requiredRole: 'Backend'
            },
            {
              id: 'tf-t2',
              title: 'Drag-and-drop board UI',
              description: 'React DnD board with column and card CRUD operations',
              startDate: new Date('2026-01-19'),
              endDate: new Date('2026-01-30'),
              status: 'completed',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Sara Lee',
              requiredRole: 'Frontend',
              dependencies: { blockedBy: ['tf-t1'] }
            },
            {
              id: 'tf-t3',
              title: 'Card detail drawer',
              description: 'Slide-out with description, labels, assignee, due date',
              startDate: new Date('2026-02-02'),
              endDate: new Date('2026-02-06'),
              status: 'completed',
              storyPoints: 3,
              effortDays: 3,
              assignedTo: 'Sara Lee',
              requiredRole: 'Frontend',
              dependencies: { blockedBy: ['tf-t2'] }
            },
            {
              id: 'tf-t4',
              title: 'Board E2E test suite',
              description: 'Playwright tests covering all board interactions',
              startDate: new Date('2026-02-09'),
              endDate: new Date('2026-02-13'),
              status: 'completed',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Wei Zhang',
              requiredRole: 'QA',
              dependencies: { blockedBy: ['tf-t2'] }
            }
          ]
        },
        {
          id: 'tf-f2',
          name: '🔍 Search & Filters',
          tickets: [
            {
              id: 'tf-t5',
              title: 'Full-text search index',
              description: 'PostgreSQL tsvector index on tasks, boards, and comments',
              startDate: new Date('2026-02-16'),
              endDate: new Date('2026-02-20'),
              status: 'completed',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Alex Chen',
              requiredRole: 'Backend'
            },
            {
              id: 'tf-t6',
              title: 'Search UI + filter bar',
              description: 'Global search input + label, assignee, date filter chips',
              startDate: new Date('2026-02-23'),
              endDate: new Date('2026-02-27'),
              status: 'completed',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Sara Lee',
              requiredRole: 'Frontend',
              dependencies: { blockedBy: ['tf-t5'] }
            },
            {
              id: 'tf-t7',
              title: 'Saved filters & view persistence',
              description: 'User-saved filter presets stored in localStorage and backend',
              startDate: new Date('2026-03-02'),
              endDate: new Date('2026-03-06'),
              status: 'in-progress',
              storyPoints: 3,
              effortDays: 3,
              assignedTo: 'Alex Chen',
              requiredRole: 'Backend',
              dependencies: { blockedBy: ['tf-t5'] }
            },
            {
              id: 'tf-t8',
              title: 'Search regression tests',
              description: 'Cypress tests for search, filter, and sort scenarios',
              startDate: new Date('2026-03-09'),
              endDate: new Date('2026-03-13'),
              status: 'planned',
              storyPoints: 3,
              effortDays: 3,
              assignedTo: 'Wei Zhang',
              requiredRole: 'QA',
              dependencies: { blockedBy: ['tf-t7'] }
            }
          ]
        }
      ],
      sprints: [
        {
          id: 'tf-s1',
          name: 'Sprint 1 — Foundation',
          startDate: new Date('2026-01-12'),
          endDate: new Date('2026-01-23')
        },
        {
          id: 'tf-s2',
          name: 'Sprint 2 — Board UI',
          startDate: new Date('2026-01-26'),
          endDate: new Date('2026-02-06')
        },
        {
          id: 'tf-s3',
          name: 'Sprint 3 — Interactions',
          startDate: new Date('2026-02-09'),
          endDate: new Date('2026-02-20')
        },
        {
          id: 'tf-s4',
          name: 'Sprint 4 — Search',
          startDate: new Date('2026-02-23'),
          endDate: new Date('2026-03-06')
        },
        {
          id: 'tf-s5',
          name: 'Sprint 5 — QA & Launch',
          startDate: new Date('2026-03-09'),
          endDate: new Date('2026-03-20')
        }
      ]
    },
    {
      id: 'tf-rel-2',
      name: 'v2.0 — Team Collaboration',
      startDate: new Date('2026-04-06'),
      endDate: new Date('2026-06-26'),
      storyPointMapping: SP_PRESETS.fibonacci,
      milestones: [
        {
          id: 'tf-ms-4',
          releaseId: 'tf-rel-2',
          name: 'Private Beta',
          type: 'Testing',
          dateType: 'single',
          startDate: new Date('2026-05-22'),
          description: 'Limited beta rollout to design partners',
          isBlocking: false,
          order: 1
        },
        {
          id: 'tf-ms-5',
          releaseId: 'tf-rel-2',
          name: 'GA Launch',
          type: 'Launch',
          dateType: 'single',
          startDate: new Date('2026-06-26'),
          description: 'General availability launch',
          isBlocking: false,
          order: 2
        }
      ],
      features: [
        {
          id: 'tf-f3',
          name: '👥 Real-time Collaboration',
          tickets: [
            {
              id: 'tf-t9',
              title: 'WebSocket presence server',
              description: 'Node.js WS server for real-time card locking and cursor presence',
              startDate: new Date('2026-04-06'),
              endDate: new Date('2026-04-17'),
              status: 'planned',
              storyPoints: 13,
              effortDays: 10,
              assignedTo: 'Alex Chen',
              requiredRole: 'Backend'
            },
            {
              id: 'tf-t10',
              title: 'Live board multiplayer UI',
              description: 'Optimistic updates and conflict resolution indicators',
              startDate: new Date('2026-04-20'),
              endDate: new Date('2026-05-01'),
              status: 'planned',
              storyPoints: 13,
              effortDays: 10,
              assignedTo: 'Sara Lee',
              requiredRole: 'Frontend',
              dependencies: { blockedBy: ['tf-t9'] }
            },
            {
              id: 'tf-t11',
              title: 'Conflict resolution E2E tests',
              description: 'Multi-user concurrent editing scenarios',
              startDate: new Date('2026-05-04'),
              endDate: new Date('2026-05-08'),
              status: 'planned',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Wei Zhang',
              requiredRole: 'QA',
              dependencies: { blockedBy: ['tf-t10'] }
            }
          ]
        },
        {
          id: 'tf-f4',
          name: '🔔 Notifications',
          tickets: [
            {
              id: 'tf-t12',
              title: 'Notification service + email delivery',
              description: 'Event-driven engine with in-app and email delivery',
              startDate: new Date('2026-05-11'),
              endDate: new Date('2026-05-22'),
              status: 'planned',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Alex Chen',
              requiredRole: 'Backend'
            },
            {
              id: 'tf-t13',
              title: 'In-app notification bell + feed',
              description: 'Real-time notification indicator and paginated feed UI',
              startDate: new Date('2026-05-25'),
              endDate: new Date('2026-05-29'),
              status: 'planned',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Sara Lee',
              requiredRole: 'Frontend',
              dependencies: { blockedBy: ['tf-t12'] }
            }
          ]
        },
        {
          id: 'tf-f5',
          name: '🔐 Role & Permission Management',
          tickets: [
            {
              id: 'tf-t14',
              title: 'RBAC model + API guards',
              description: 'Workspace Owner, Editor, Viewer roles with middleware enforcement',
              startDate: new Date('2026-06-01'),
              endDate: new Date('2026-06-05'),
              status: 'planned',
              storyPoints: 8,
              effortDays: 5,
              assignedTo: 'Alex Chen',
              requiredRole: 'Backend'
            },
            {
              id: 'tf-t15',
              title: 'Settings UI — team & roles',
              description: 'Invite members, assign roles, revoke access',
              startDate: new Date('2026-06-08'),
              endDate: new Date('2026-06-12'),
              status: 'planned',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Sara Lee',
              requiredRole: 'Frontend',
              dependencies: { blockedBy: ['tf-t14'] }
            },
            {
              id: 'tf-t16',
              title: 'Permission regression test suite',
              description: 'Role-based access control test coverage',
              startDate: new Date('2026-06-15'),
              endDate: new Date('2026-06-19'),
              status: 'planned',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Wei Zhang',
              requiredRole: 'QA',
              dependencies: { blockedBy: ['tf-t15'] }
            }
          ]
        }
      ],
      sprints: [
        {
          id: 'tf-s6',
          name: 'Sprint 1 — WS Foundation',
          startDate: new Date('2026-04-06'),
          endDate: new Date('2026-04-17')
        },
        {
          id: 'tf-s7',
          name: 'Sprint 2 — Multiplayer UI',
          startDate: new Date('2026-04-20'),
          endDate: new Date('2026-05-01')
        },
        {
          id: 'tf-s8',
          name: 'Sprint 3 — Notifications',
          startDate: new Date('2026-05-04'),
          endDate: new Date('2026-05-15')
        },
        {
          id: 'tf-s9',
          name: 'Sprint 4 — Roles & Perms',
          startDate: new Date('2026-05-25'),
          endDate: new Date('2026-06-05')
        },
        {
          id: 'tf-s10',
          name: 'Sprint 5 — Hardening',
          startDate: new Date('2026-06-08'),
          endDate: new Date('2026-06-19')
        }
      ]
    }
  ]
};

// ===========================================
// PRODUCT 2: � PAYSYNC (WEB — PAYMENTS PLATFORM)
// ===========================================
const product2: Product = {
  id: 'paysync-01',
  name: '💳 PaySync — Payments Platform',
  releases: [
    {
      id: 'ps-rel-1',
      name: 'v1.0 — Payment Gateway',
      startDate: new Date('2026-01-05'),
      endDate: new Date('2026-03-20'),
      storyPointMapping: SP_PRESETS.fibonacci,
      milestones: [
        {
          id: 'ps-ms-1',
          releaseId: 'ps-rel-1',
          name: 'Security Audit',
          type: 'Approval',
          dateType: 'single',
          startDate: new Date('2026-02-20'),
          description: 'External penetration test sign-off',
          isBlocking: true,
          order: 1
        },
        {
          id: 'ps-ms-2',
          releaseId: 'ps-rel-1',
          name: 'PCI-DSS Compliance Review',
          type: 'Approval',
          dateType: 'single',
          startDate: new Date('2026-03-06'),
          description: 'Compliance team sign-off required before go-live',
          isBlocking: true,
          order: 2
        },
        {
          id: 'ps-ms-3',
          releaseId: 'ps-rel-1',
          name: 'Production Go-Live',
          type: 'Launch',
          dateType: 'single',
          startDate: new Date('2026-03-20'),
          description: 'Payment gateway live for pilot customers',
          isBlocking: false,
          order: 3
        }
      ],
      features: [
        {
          id: 'ps-f1',
          name: '💰 Payment Processing',
          tickets: [
            {
              id: 'ps-t1',
              title: 'Stripe & Braintree integration layer',
              description: 'Abstracted payment provider SDK with unified charge and refund API',
              startDate: new Date('2026-01-05'),
              endDate: new Date('2026-01-16'),
              status: 'completed',
              storyPoints: 13,
              effortDays: 10,
              assignedTo: 'Jordan Blake',
              requiredRole: 'Backend'
            },
            {
              id: 'ps-t2',
              title: 'Payment intent state machine',
              description: 'Idempotent payment lifecycle: pending → authorized → captured/failed',
              startDate: new Date('2026-01-19'),
              endDate: new Date('2026-01-30'),
              status: 'completed',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Jordan Blake',
              requiredRole: 'Backend',
              dependencies: { blockedBy: ['ps-t1'] }
            },
            {
              id: 'ps-t3',
              title: 'Checkout UI flow',
              description: 'Card input, 3DS redirect, confirmation screen',
              startDate: new Date('2026-02-02'),
              endDate: new Date('2026-02-13'),
              status: 'completed',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Priya Sharma',
              requiredRole: 'Frontend',
              dependencies: { blockedBy: ['ps-t2'] }
            },
            {
              id: 'ps-t4',
              title: 'Payment integration tests',
              description: 'Sandbox E2E tests covering success, decline, 3DS flows',
              startDate: new Date('2026-02-16'),
              endDate: new Date('2026-02-20'),
              status: 'in-progress',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Amara Osei',
              requiredRole: 'QA',
              dependencies: { blockedBy: ['ps-t3'] }
            }
          ]
        },
        {
          id: 'ps-f2',
          name: '🔐 Auth & Security',
          tickets: [
            {
              id: 'ps-t5',
              title: 'API key management + JWT auth',
              description: 'Scoped API key generation, rotation, and JWT session auth',
              startDate: new Date('2026-01-26'),
              endDate: new Date('2026-02-06'),
              status: 'completed',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Chris Novak',
              requiredRole: 'Fullstack'
            },
            {
              id: 'ps-t6',
              title: 'Webhook signature verification',
              description: 'HMAC-SHA256 verification for incoming webhook payloads',
              startDate: new Date('2026-02-09'),
              endDate: new Date('2026-02-13'),
              status: 'completed',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Jordan Blake',
              requiredRole: 'Backend',
              dependencies: { blockedBy: ['ps-t5'] }
            },
            {
              id: 'ps-t7',
              title: 'Security hardening & pentest fixes',
              description: 'Remediate pentest findings: rate limiting, header hardening',
              startDate: new Date('2026-02-23'),
              endDate: new Date('2026-03-06'),
              status: 'in-progress',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Chris Novak',
              requiredRole: 'Fullstack',
              dependencies: { blockedBy: ['ps-t5'] }
            }
          ]
        },
        {
          id: 'ps-f3',
          name: '🔗 Webhooks & Notifications',
          tickets: [
            {
              id: 'ps-t8',
              title: '⚡ CONFLICT: Webhook event dispatcher',
              description: 'Retry-backed outbound webhook delivery — assignee conflict with ps-t4',
              startDate: new Date('2026-02-16'),
              endDate: new Date('2026-02-27'),
              status: 'planned',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Jordan Blake',
              requiredRole: 'Backend',
              dependencies: { blockedBy: ['ps-t6'] }
            },
            {
              id: 'ps-t9',
              title: 'Webhook dashboard UI',
              description: 'Event log, delivery status, manual retry UI',
              startDate: new Date('2026-03-02'),
              endDate: new Date('2026-03-06'),
              status: 'planned',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Priya Sharma',
              requiredRole: 'Frontend',
              dependencies: { blockedBy: ['ps-t8'] }
            }
          ]
        }
      ],
      sprints: [
        {
          id: 'ps-s1',
          name: 'Sprint 1 — Provider Integration',
          startDate: new Date('2026-01-05'),
          endDate: new Date('2026-01-16')
        },
        {
          id: 'ps-s2',
          name: 'Sprint 2 — Auth & State Machine',
          startDate: new Date('2026-01-19'),
          endDate: new Date('2026-01-30')
        },
        {
          id: 'ps-s3',
          name: 'Sprint 3 — Checkout & Security',
          startDate: new Date('2026-02-02'),
          endDate: new Date('2026-02-13')
        },
        {
          id: 'ps-s4',
          name: 'Sprint 4 — Webhooks & Testing',
          startDate: new Date('2026-02-16'),
          endDate: new Date('2026-02-27')
        },
        {
          id: 'ps-s5',
          name: 'Sprint 5 — Hardening & Go-Live',
          startDate: new Date('2026-03-02'),
          endDate: new Date('2026-03-13')
        }
      ]
    },
    {
      id: 'ps-rel-2',
      name: 'v1.5 — Analytics & Reporting',
      startDate: new Date('2026-03-30'),
      endDate: new Date('2026-06-12'),
      storyPointMapping: SP_PRESETS.fibonacci,
      milestones: [
        {
          id: 'ps-ms-4',
          releaseId: 'ps-rel-2',
          name: 'Beta Rollout',
          type: 'Testing',
          dateType: 'single',
          startDate: new Date('2026-05-15'),
          description: 'Beta access for pilot merchants',
          isBlocking: false,
          order: 1
        },
        {
          id: 'ps-ms-5',
          releaseId: 'ps-rel-2',
          name: 'General Availability',
          type: 'Launch',
          dateType: 'single',
          startDate: new Date('2026-06-12'),
          description: 'Analytics GA release',
          isBlocking: false,
          order: 2
        }
      ],
      features: [
        {
          id: 'ps-f4',
          name: '📊 Merchant Dashboard',
          tickets: [
            {
              id: 'ps-t10',
              title: 'Analytics data aggregation pipeline',
              description: 'Daily, weekly, monthly rollup jobs for revenue, volume, failure rates',
              startDate: new Date('2026-03-30'),
              endDate: new Date('2026-04-10'),
              status: 'planned',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Jordan Blake',
              requiredRole: 'Backend'
            },
            {
              id: 'ps-t11',
              title: 'Dashboard charts & KPI cards',
              description: 'Recharts revenue charts, transaction volume, conversion funnel',
              startDate: new Date('2026-04-13'),
              endDate: new Date('2026-04-24'),
              status: 'planned',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Priya Sharma',
              requiredRole: 'Frontend',
              dependencies: { blockedBy: ['ps-t10'] }
            },
            {
              id: 'ps-t12',
              title: 'Date range filter + drill-down',
              description: 'Interactive date picker with chart drill-down to transaction level',
              startDate: new Date('2026-04-27'),
              endDate: new Date('2026-05-01'),
              status: 'planned',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Priya Sharma',
              requiredRole: 'Frontend',
              dependencies: { blockedBy: ['ps-t11'] }
            }
          ]
        },
        {
          id: 'ps-f5',
          name: '📤 Export & Reconciliation',
          tickets: [
            {
              id: 'ps-t13',
              title: '🏖️ PTO CONFLICT: CSV & PDF export service',
              description: 'Async report generation with download link — during PTO (May 4-8)',
              startDate: new Date('2026-04-27'),
              endDate: new Date('2026-05-08'),
              status: 'planned',
              storyPoints: 5,
              effortDays: 8,
              assignedTo: 'Chris Novak',
              requiredRole: 'Fullstack'
            },
            {
              id: 'ps-t14',
              title: 'Reconciliation report UI',
              description: 'Settled vs pending breakdown with mismatch flagging',
              startDate: new Date('2026-05-11'),
              endDate: new Date('2026-05-15'),
              status: 'planned',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Priya Sharma',
              requiredRole: 'Frontend',
              dependencies: { blockedBy: ['ps-t12'] }
            },
            {
              id: 'ps-t15',
              title: 'Analytics QA test coverage',
              description: 'Data accuracy checks, export validation, filter regression',
              startDate: new Date('2026-05-18'),
              endDate: new Date('2026-05-22'),
              status: 'planned',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Amara Osei',
              requiredRole: 'QA',
              dependencies: { blockedBy: ['ps-t14'] }
            }
          ]
        }
      ],
      sprints: [
        {
          id: 'ps-s6',
          name: 'Sprint 1 — Data Pipeline',
          startDate: new Date('2026-03-30'),
          endDate: new Date('2026-04-10')
        },
        {
          id: 'ps-s7',
          name: 'Sprint 2 — Dashboard UI',
          startDate: new Date('2026-04-13'),
          endDate: new Date('2026-04-24')
        },
        {
          id: 'ps-s8',
          name: 'Sprint 3 — Filters & Export',
          startDate: new Date('2026-04-27'),
          endDate: new Date('2026-05-08')
        },
        {
          id: 'ps-s9',
          name: 'Sprint 4 — Reconciliation',
          startDate: new Date('2026-05-11'),
          endDate: new Date('2026-05-22')
        },
        {
          id: 'ps-s10',
          name: 'Sprint 5 — QA & GA',
          startDate: new Date('2026-05-25'),
          endDate: new Date('2026-06-05')
        }
      ]
    }
  ]
};

// ===========================================
// PRODUCT 3: 📱 TRAILSYNC (MOBILE — OUTDOOR ACTIVITY TRACKER)
// ===========================================
const product3: Product = {
  id: 'trailsync-01',
  name: '📱 TrailSync — Outdoor Activity Tracker',
  releases: [
    {
      id: 'ts-rel-1',
      name: 'v1.0 — App Store Launch',
      startDate: new Date('2026-02-02'),
      endDate: new Date('2026-05-29'),
      storyPointMapping: SP_PRESETS.fibonacci,
      milestones: [
        {
          id: 'ts-ms-1',
          releaseId: 'ts-rel-1',
          name: 'Feature Freeze',
          type: 'Freeze',
          dateType: 'single',
          startDate: new Date('2026-04-24'),
          description: 'No new features — stabilization only',
          isBlocking: true,
          order: 1
        },
        {
          id: 'ts-ms-2',
          releaseId: 'ts-rel-1',
          name: 'App Store Submission',
          type: 'Deployment',
          dateType: 'single',
          startDate: new Date('2026-05-15'),
          description: 'Submit iOS & Android builds for review',
          isBlocking: true,
          order: 2
        },
        {
          id: 'ts-ms-3',
          releaseId: 'ts-rel-1',
          name: 'Launch Day',
          type: 'Launch',
          dateType: 'single',
          startDate: new Date('2026-05-29'),
          description: 'Public availability on App Store & Play Store',
          isBlocking: false,
          order: 3
        }
      ],
      features: [
        {
          id: 'ts-f1',
          name: '📍 Activity Tracking',
          tickets: [
            {
              id: 'ts-t1',
              title: 'GPS track recording — iOS',
              description: 'Core Location framework integration, background recording, GPX export',
              startDate: new Date('2026-02-02'),
              endDate: new Date('2026-02-13'),
              status: 'completed',
              storyPoints: 13,
              effortDays: 10,
              assignedTo: 'Kenji Mori',
              requiredRole: 'iOS'
            },
            {
              id: 'ts-t2',
              title: 'GPS track recording — Android',
              description: 'FusedLocationProvider integration, foreground service, FIT export',
              startDate: new Date('2026-02-02'),
              endDate: new Date('2026-02-13'),
              status: 'completed',
              storyPoints: 13,
              effortDays: 10,
              assignedTo: 'Farah Hassan',
              requiredRole: 'Android'
            },
            {
              id: 'ts-t3',
              title: 'Elevation & stats engine',
              description: 'REST API: compute distance, elevation gain, pace, calories from GPX',
              startDate: new Date('2026-02-16'),
              endDate: new Date('2026-02-27'),
              status: 'completed',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Lin Wei',
              requiredRole: 'Backend',
              dependencies: { blockedBy: ['ts-t1', 'ts-t2'] }
            },
            {
              id: 'ts-t4',
              title: 'Activity stats screen — iOS',
              description: 'Post-activity summary: map replay, elevation chart, stats breakdown',
              startDate: new Date('2026-03-02'),
              endDate: new Date('2026-03-13'),
              status: 'completed',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Kenji Mori',
              requiredRole: 'iOS',
              dependencies: { blockedBy: ['ts-t3'] }
            },
            {
              id: 'ts-t5',
              title: 'Activity stats screen — Android',
              description: 'Post-activity summary with Jetpack Compose UI',
              startDate: new Date('2026-03-02'),
              endDate: new Date('2026-03-13'),
              status: 'completed',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Farah Hassan',
              requiredRole: 'Android',
              dependencies: { blockedBy: ['ts-t3'] }
            }
          ]
        },
        {
          id: 'ts-f2',
          name: '🗺️ Maps & Routes',
          tickets: [
            {
              id: 'ts-t6',
              title: 'Map rendering — iOS (MapKit)',
              description: 'Overlay recorded tracks, waypoints, and route cards on MapKit',
              startDate: new Date('2026-03-16'),
              endDate: new Date('2026-03-27'),
              status: 'in-progress',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Kenji Mori',
              requiredRole: 'iOS'
            },
            {
              id: 'ts-t7',
              title: 'Map rendering — Android (Maps SDK)',
              description: 'Google Maps SDK integration with track polyline rendering',
              startDate: new Date('2026-03-16'),
              endDate: new Date('2026-03-27'),
              status: 'in-progress',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Farah Hassan',
              requiredRole: 'Android'
            },
            {
              id: 'ts-t8',
              title: 'Map UI design system',
              description: 'Design tokens and component specs for map UI across platforms',
              startDate: new Date('2026-03-02'),
              endDate: new Date('2026-03-13'),
              status: 'in-progress',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Mei Lin',
              requiredRole: 'Designer'
            }
          ]
        },
        {
          id: 'ts-f3',
          name: '👤 User Profile & History',
          tickets: [
            {
              id: 'ts-t9',
              title: 'User profile API + activity history',
              description: 'User profile CRUD, paginated activity history, personal records',
              startDate: new Date('2026-03-30'),
              endDate: new Date('2026-04-10'),
              status: 'planned',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Lin Wei',
              requiredRole: 'Backend'
            },
            {
              id: 'ts-t10',
              title: 'Profile & history screens — iOS',
              description: 'Profile photo, stats summary, scrollable activity list',
              startDate: new Date('2026-04-13'),
              endDate: new Date('2026-04-17'),
              status: 'planned',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Kenji Mori',
              requiredRole: 'iOS',
              dependencies: { blockedBy: ['ts-t9'] }
            },
            {
              id: 'ts-t11',
              title: 'Profile & history screens — Android',
              description: 'Profile screen with Jetpack Compose, RecyclerView activity list',
              startDate: new Date('2026-04-13'),
              endDate: new Date('2026-04-17'),
              status: 'planned',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Farah Hassan',
              requiredRole: 'Android',
              dependencies: { blockedBy: ['ts-t9'] }
            },
            {
              id: 'ts-t12',
              title: 'Cross-platform QA — launch readiness',
              description: 'Device matrix testing, regression suite, App Store compliance',
              startDate: new Date('2026-04-27'),
              endDate: new Date('2026-05-08'),
              status: 'planned',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Tariq Rasheed',
              requiredRole: 'QA',
              dependencies: { blockedBy: ['ts-t10', 'ts-t11'] }
            }
          ]
        }
      ],
      sprints: [
        {
          id: 'ts-s1',
          name: 'Sprint 1 — GPS Core',
          startDate: new Date('2026-02-02'),
          endDate: new Date('2026-02-13')
        },
        {
          id: 'ts-s2',
          name: 'Sprint 2 — Stats Engine',
          startDate: new Date('2026-02-16'),
          endDate: new Date('2026-02-27')
        },
        {
          id: 'ts-s3',
          name: 'Sprint 3 — Activity UI',
          startDate: new Date('2026-03-02'),
          endDate: new Date('2026-03-13')
        },
        {
          id: 'ts-s4',
          name: 'Sprint 4 — Maps',
          startDate: new Date('2026-03-16'),
          endDate: new Date('2026-03-27')
        },
        {
          id: 'ts-s5',
          name: 'Sprint 5 — Profile',
          startDate: new Date('2026-03-30'),
          endDate: new Date('2026-04-10')
        },
        {
          id: 'ts-s6',
          name: 'Sprint 6 — Final QA',
          startDate: new Date('2026-04-27'),
          endDate: new Date('2026-05-08')
        }
      ]
    },
    {
      id: 'ts-rel-2',
      name: 'v1.1 — Social & Offline Mode',
      startDate: new Date('2026-06-01'),
      endDate: new Date('2026-08-28'),
      storyPointMapping: SP_PRESETS.fibonacci,
      milestones: [
        {
          id: 'ts-ms-4',
          releaseId: 'ts-rel-2',
          name: 'Internal Beta',
          type: 'Testing',
          dateType: 'single',
          startDate: new Date('2026-07-31'),
          description: 'Internal team + design partners testing',
          isBlocking: false,
          order: 1
        },
        {
          id: 'ts-ms-5',
          releaseId: 'ts-rel-2',
          name: 'App Store Update',
          type: 'Launch',
          dateType: 'single',
          startDate: new Date('2026-08-28'),
          description: 'v1.1 update submission and release',
          isBlocking: false,
          order: 2
        }
      ],
      features: [
        {
          id: 'ts-f4',
          name: '👥 Social Feed',
          tickets: [
            {
              id: 'ts-t13',
              title: 'Follow/follower graph API',
              description: 'Follow, unfollow, block; feed generation service',
              startDate: new Date('2026-06-01'),
              endDate: new Date('2026-06-12'),
              status: 'planned',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Lin Wei',
              requiredRole: 'Backend'
            },
            {
              id: 'ts-t14',
              title: '🏖️ PTO CONFLICT: Activity feed — iOS',
              description: 'Social feed with likes, kudos, comments — during PTO (Jun 22-26)',
              startDate: new Date('2026-06-15'),
              endDate: new Date('2026-06-26'),
              status: 'planned',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Kenji Mori',
              requiredRole: 'iOS',
              dependencies: { blockedBy: ['ts-t13'] }
            },
            {
              id: 'ts-t15',
              title: 'Activity feed — Android',
              description: 'Social feed with Jetpack Compose and pull-to-refresh',
              startDate: new Date('2026-06-15'),
              endDate: new Date('2026-06-26'),
              status: 'planned',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Farah Hassan',
              requiredRole: 'Android',
              dependencies: { blockedBy: ['ts-t13'] }
            }
          ]
        },
        {
          id: 'ts-f5',
          name: '📵 Offline Sync',
          tickets: [
            {
              id: 'ts-t16',
              title: 'Local SQLite store + sync engine — iOS',
              description: 'CRDT-based offline sync for activities when offline',
              startDate: new Date('2026-06-29'),
              endDate: new Date('2026-07-10'),
              status: 'planned',
              storyPoints: 13,
              effortDays: 10,
              assignedTo: 'Kenji Mori',
              requiredRole: 'iOS'
            },
            {
              id: 'ts-t17',
              title: 'Android offline store + sync',
              description: 'Room database + WorkManager sync adapter',
              startDate: new Date('2026-06-29'),
              endDate: new Date('2026-07-10'),
              status: 'planned',
              storyPoints: 13,
              effortDays: 10,
              assignedTo: 'Farah Hassan',
              requiredRole: 'Android'
            },
            {
              id: 'ts-t18',
              title: 'Offline/online regression testing',
              description: 'Network condition simulation, sync conflict scenarios',
              startDate: new Date('2026-07-13'),
              endDate: new Date('2026-07-24'),
              status: 'planned',
              storyPoints: 8,
              effortDays: 8,
              assignedTo: 'Tariq Rasheed',
              requiredRole: 'QA',
              dependencies: { blockedBy: ['ts-t16', 'ts-t17'] }
            }
          ]
        },
        {
          id: 'ts-f6',
          name: '🔔 Push Notifications',
          tickets: [
            {
              id: 'ts-t19',
              title: 'Push notification service (APNs + FCM)',
              description: 'Unified push dispatcher for iOS APNs and Android FCM',
              startDate: new Date('2026-07-27'),
              endDate: new Date('2026-08-07'),
              status: 'planned',
              storyPoints: 5,
              effortDays: 8,
              assignedTo: 'Lin Wei',
              requiredRole: 'Backend'
            },
            {
              id: 'ts-t20',
              title: 'Notification preferences UI',
              description: 'Per-type notification preferences, quiet hours, batch digest',
              startDate: new Date('2026-08-10'),
              endDate: new Date('2026-08-14'),
              status: 'planned',
              storyPoints: 5,
              effortDays: 5,
              assignedTo: 'Mei Lin',
              requiredRole: 'Designer'
            }
          ]
        }
      ],
      sprints: [
        {
          id: 'ts-s7',
          name: 'Sprint 1 — Social Graph',
          startDate: new Date('2026-06-01'),
          endDate: new Date('2026-06-12')
        },
        {
          id: 'ts-s8',
          name: 'Sprint 2 — Feed UI',
          startDate: new Date('2026-06-15'),
          endDate: new Date('2026-06-26')
        },
        {
          id: 'ts-s9',
          name: 'Sprint 3 — Offline Core',
          startDate: new Date('2026-06-29'),
          endDate: new Date('2026-07-10')
        },
        {
          id: 'ts-s10',
          name: 'Sprint 4 — Sync Testing',
          startDate: new Date('2026-07-13'),
          endDate: new Date('2026-07-24')
        },
        {
          id: 'ts-s11',
          name: 'Sprint 5 — Push & Polish',
          startDate: new Date('2026-07-27'),
          endDate: new Date('2026-08-07')
        },
        {
          id: 'ts-s12',
          name: 'Sprint 6 — Release Prep',
          startDate: new Date('2026-08-10'),
          endDate: new Date('2026-08-21')
        }
      ]
    }
  ]
};


export const mockTeamMembers: TeamMember[] = [
  // ===========================================
  // PRODUCT 1: TASKFLOW PRO TEAM
  // ===========================================
  {
    id: 'tm-tf-1',
    name: 'Alex Chen',
    role: 'Backend',
    experienceLevel: 'Senior',
    productId: 'taskflow-01',
    velocityMultiplier: 1.2,
    notes: 'Backend lead, API architecture',
    pto: [
      { id: 'pto-tf1', name: 'Vacation', startDate: new Date('2026-05-18'), endDate: new Date('2026-05-22') }
    ]
  },
  {
    id: 'tm-tf-2',
    name: 'Sara Lee',
    role: 'Frontend',
    experienceLevel: 'Senior',
    productId: 'taskflow-01',
    velocityMultiplier: 1.2,
    notes: 'Frontend specialist, React + design systems',
    pto: [
      { id: 'pto-tf2', name: 'Conference', startDate: new Date('2026-06-22'), endDate: new Date('2026-06-26') }
    ]
  },
  {
    id: 'tm-tf-3',
    name: 'Wei Zhang',
    role: 'QA',
    experienceLevel: 'Mid',
    productId: 'taskflow-01',
    velocityMultiplier: 1.0,
    notes: 'Test automation, API testing',
    pto: []
  },

  // ===========================================
  // PRODUCT 2: PAYSYNC TEAM
  // ===========================================
  {
    id: 'tm-ps-1',
    name: 'Jordan Blake',
    role: 'Backend',
    experienceLevel: 'Lead',
    productId: 'paysync-01',
    velocityMultiplier: 1.3,
    notes: 'Payments architecture lead, PCI compliance',
    pto: [
      { id: 'pto-ps1', name: 'Family Leave', startDate: new Date('2026-04-13'), endDate: new Date('2026-04-17') }
    ]
  },
  {
    id: 'tm-ps-2',
    name: 'Priya Sharma',
    role: 'Frontend',
    experienceLevel: 'Senior',
    productId: 'paysync-01',
    velocityMultiplier: 1.2,
    notes: 'Dashboard UI, data visualisation',
    pto: []
  },
  {
    id: 'tm-ps-3',
    name: 'Chris Novak',
    role: 'Fullstack',
    experienceLevel: 'Senior',
    productId: 'paysync-01',
    velocityMultiplier: 1.2,
    notes: 'Webhook infrastructure and integrations',
    pto: [
      { id: 'pto-ps2', name: 'Vacation', startDate: new Date('2026-05-04'), endDate: new Date('2026-05-08') }
    ]
  },
  {
    id: 'tm-ps-4',
    name: 'Amara Osei',
    role: 'QA',
    experienceLevel: 'Senior',
    productId: 'paysync-01',
    velocityMultiplier: 1.2,
    notes: 'Payments QA, security testing',
    pto: []
  },

  // ===========================================
  // PRODUCT 3: TRAILSYNC TEAM
  // ===========================================
  {
    id: 'tm-ts-1',
    name: 'Kenji Mori',
    role: 'iOS',
    experienceLevel: 'Lead',
    productId: 'trailsync-01',
    velocityMultiplier: 1.3,
    notes: 'iOS lead, Core Location & HealthKit expert',
    pto: [
      { id: 'pto-ts1', name: 'Vacation', startDate: new Date('2026-06-22'), endDate: new Date('2026-06-26') }
    ]
  },
  {
    id: 'tm-ts-2',
    name: 'Farah Hassan',
    role: 'Android',
    experienceLevel: 'Senior',
    productId: 'trailsync-01',
    velocityMultiplier: 1.2,
    notes: 'Android lead, Jetpack Compose specialist',
    pto: [
      { id: 'pto-ts2', name: 'Family Trip', startDate: new Date('2026-07-20'), endDate: new Date('2026-07-24') }
    ]
  },
  {
    id: 'tm-ts-3',
    name: 'Lin Wei',
    role: 'Backend',
    experienceLevel: 'Senior',
    productId: 'trailsync-01',
    velocityMultiplier: 1.2,
    notes: 'API and sync engine architect',
    pto: []
  },
  {
    id: 'tm-ts-4',
    name: 'Mei Lin',
    role: 'Designer',
    experienceLevel: 'Mid',
    productId: 'trailsync-01',
    velocityMultiplier: 1.0,
    notes: 'Mobile UX and design systems',
    pto: []
  },
  {
    id: 'tm-ts-5',
    name: 'Tariq Rasheed',
    role: 'QA',
    experienceLevel: 'Mid',
    productId: 'trailsync-01',
    velocityMultiplier: 1.0,
    notes: 'Mobile QA, device matrix testing',
    pto: []
  }
];

export const mockHolidays: Holiday[] = [
  {
    id: 'hol-1',
    name: "New Year's Day",
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-01-01')
  },
  {
    id: 'hol-2',
    name: "Martin Luther King Jr. Day",
    startDate: new Date('2026-01-19'),
    endDate: new Date('2026-01-19')
  },
  {
    id: 'hol-3',
    name: "Presidents' Day",
    startDate: new Date('2026-02-16'),
    endDate: new Date('2026-02-16')
  },
  {
    id: 'hol-4',
    name: 'Good Friday',
    startDate: new Date('2026-04-03'),
    endDate: new Date('2026-04-03')
  },
  {
    id: 'hol-5',
    name: 'Memorial Day',
    startDate: new Date('2026-05-25'),
    endDate: new Date('2026-05-25')
  },
  {
    id: 'hol-6',
    name: 'Independence Day',
    startDate: new Date('2026-07-04'),
    endDate: new Date('2026-07-04')
  },
  {
    id: 'hol-7',
    name: 'Company Offsite',
    startDate: new Date('2026-03-19'),
    endDate: new Date('2026-03-20')
  }
];



// ===========================================
// EXPORTS AND HELPER FUNCTIONS
// ===========================================
export const mockProducts: Product[] = [product1, product2, product3];

export function findReleaseById(releaseId: string): { product: Product; release: Release } | null {
  for (const product of mockProducts) {
    const release = product.releases.find(r => r.id === releaseId);
    if (release) return { product, release };
  }
  return null;
}

export function getTeamMembersByProduct(productId: string, allMembers: TeamMember[] = mockTeamMembers): TeamMember[] {
  return allMembers.filter(m => m.productId === productId);
}
